name: 'Deploy üöÄ'

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy-web:
    name: 'Web üåê'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-web
      cancel-in-progress: true
    permissions:
      contents: write
    environment:
      name: production
      url: FILL_ME_LATER
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name GitHub_Runner
      - run: bun install
      - run: npm --no-git-tag-version version ${{  github.ref_name }}
      - run: bun run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch: main
          command: pages deploy .svelte-kit/cloudflare --project-name=theo-challengers

  deploy-desktop:
    name: ${{ matrix.settings.name }}
    permissions:
      contents: write
      discussions: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - name: 'MacOS üçè'
            platform: 'macos-latest'
          - name: 'Linux üêß'
            platform: 'ubuntu-latest'
          - name: 'Windows ü™ü'
            platform: 'windows-latest'
    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v6
      - if: matrix.settings.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: dtolnay/rust-toolchain@stable
      - uses: oven-sh/setup-bun@v2
      - run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name GitHub_Runner
      - run: bun install
      - run: npm --no-git-tag-version version ${{ github.ref_name }}
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{  github.ref_name }}
          releaseName: ${{  github.ref_name }}
          releaseDraft: false
          prerelease: false

  deploy-android:
    name: 'Android ü§ñ'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      WEBISTE: FILL_ME_LATER
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: android-actions/setup-android@v3
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
          mobile: 'android'

  deploy-ios:
    name: 'iOS üçè'
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      WEBISTE: FILL_ME_LATER
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
          mobile: 'ios'