name: 'Deploy üöÄ'

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy-web:
    name: 'Web üåê'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-web
      cancel-in-progress: true
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v6
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - run: bun run build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=theo-challengers

  deploy-windows:
    name: Windows ü™ü
    permissions:
      contents: write
      discussions: write
    environment:
      name: production
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6 
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

  deploy-macos:
    name: MacOS üçè
    permissions:
      contents: write
      discussions: write
    environment:
      name: production
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
          args: --target universal-apple-darwin

  deploy-linux:
    name: Linux üêß
    permissions:
      contents: write
      discussions: write
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

  deploy-android:
    name: 'Android ü§ñ'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v6
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: android-actions/setup-android@v3
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri android '
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

  deploy-ios:
    name: 'iOS üçè'
    runs-on: macos-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v6
      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          tag-name: ${{ github.ref_name }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: 'bun run tauri ios'
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
